### ISSUE TITLE
Figure out where to store large files

### ISSUE THREAD

**Issue by pbeshai** [social-machines/social-machines.github.io#11]
The PDF files for theses go as large as 125MB and that's too big for this repository. We will need a different place to store those files.

**Comment by pbeshai** [comment]
Currently missing these files:

decamp_phd_thesis_with_videos.pdf
mmiller_MS_thesis.pdf
gshaw_thesisfinal1.pdf
decamp_thesis.pdf
bcroy-masters-thesis.pdf
sophia_yuditskaya_thesisdoc_draft_final.pdf
Kleovoulos_(Leo)_Tsourides_SM_2010_thesis.pdf
Prashanth_ThesisFinal.pdf
tellex-phd-thesis-2010.pdf
roy ghitza bartelma.pdf
hsiao-phd-mas-20070522.pdf
orkin_mastersthesis_2007.pdf
robbel_msthesis.09.05.2007.pdf
pgorniak_thesis.pdf

**Comment by pbeshai** [comment]
I've emailed Russell and Heather about this, so hopefully we find out soon.

**Comment by sgadgets** [comment]
Thanks for handling this!

**Comment by pbeshai** [comment]
We are just going to keep using the WordPress admin tool for now.
