### ISSUE TITLE
Format Media/Publications Page

### ISSUE THREAD

**Issue by sgadgets** [social-machines/social-machines.github.io#16]
**Organization**
1. By Us
2. About Us

**By Us**
Media Analytics, Learning, Cognitive Machines, Misc/Other
1. Deb's academic papers
2. Students/Deb's academic papers
3. Deb's Ted Talk
4. Non-academic publications 

**About Us**
1. News articles 
2. Notable interviews with mention of us?
3. Tweets?

**Search Functionality**
Possible to do a tag search at the top of the page? e.g. type in Learning and results highlight/filter?

**Comment by sgadgets** [comment]
![img_3650](https://user-images.githubusercontent.com/5923906/30811608-ab70e862-a1d6-11e7-87e7-eb1c3cbb10ad.JPG)

**Comment by pbeshai** [comment]
Demo of current prototype: 

![lsm-site-filter-demo](https://user-images.githubusercontent.com/793847/31086129-094ad9a8-a767-11e7-8622-a38da5d5e99b.gif)

**Comment by pbeshai** [comment]
Note that the state of filters needs to be encoded in the URL to make it easy to send to people.

**Comment by pbeshai** [comment]
- [ ] Should add some help text and labels/placeholder for the filter controls
