### ISSUE TITLE
People styling

### ISSUE THREAD

**Issue by pbeshai** [social-machines/social-machines.github.io#8]
Right now they were just quickly thrown together using the card UI from semantic UI, which is not great really. We should at least think about how we want to show them

![image](https://user-images.githubusercontent.com/793847/30500156-266fb862-9a2b-11e7-8f44-9497fe5601f6.png)

**Comment by pbeshai** [comment]
Changed it to this:

![image](https://user-images.githubusercontent.com/793847/30501406-548b72ae-9a30-11e7-9c70-98b1973cf445.png)

**Comment by sgadgets** [comment]
Looks fantastic, thanks @pbeshai!
